package com.api.audit.feign;

import com.api.audit.context.CorrelationContext;
import com.api.audit.entity.ApiAuditLog;
import com.api.audit.event.ApiLogEvent;
import com.api.audit.util.JsonMasker;
import feign.Response;
import feign.Util;
import feign.codec.ErrorDecoder;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.time.LocalDateTime;
import lombok.RequiredArgsConstructor;
import org.slf4j.MDC;
import org.springframework.context.ApplicationEventPublisher;

/**
 * A Decorating Feign ErrorDecoder that captures outbound failure metadata for auditing.
 *
 * <p>In a professional microservices architecture, troubleshooting 4xx and 5xx errors requires
 * visibility into the error body returned by downstream systems. This class intercepts failures,
 * logs them asynchronously via {@link ApiLogEvent}, and then delegates the exception generation to
 * the next {@link ErrorDecoder} in the stack.
 *
 * <p><b>Chain Propagation:</b> This decoder is designed to wrap existing decoders. By returning the
 * result of {@code delegate.decode()}, it ensures that custom business exceptions (e.g., {@code
 * ResourceNotFoundException}) defined in the host service are still thrown correctly.
 *
 * @author Puneet Swarup
 * @see ErrorDecoder
 * @see ApiLogEvent
 */
@RequiredArgsConstructor
public class CustomFeignErrorDecoder implements ErrorDecoder {

  private final ApplicationEventPublisher publisher;
  private final String appName;

  /** The underlying decoder to which execution is delegated after auditing. */
  private final ErrorDecoder delegate;

  private final JsonMasker jsonMasker;

  /**
   * Captures the error state and delegates exception creation.
   *
   * @param methodKey the Feign method signature
   * @param response the failed HTTP response
   * @return an Exception generated by the underlying {@code delegate}
   */
  @Override
  public Exception decode(String methodKey, Response response) {
    try {
      ApiAuditLog audit = new ApiAuditLog();
      audit.setServiceName(appName);
      audit.setType("OUTGOING_ERROR");
      audit.setMethod(response.request().httpMethod().name());
      audit.setUrl(response.request().url());
      audit.setHttpStatus(response.status());
      audit.setTimestamp(LocalDateTime.now());
      audit.setCorrelationId(MDC.get(CorrelationContext.CORRELATION_ID_HEADER));

      if (response.body() != null) {
        // Read error body into a byte array for auditing
        byte[] bodyData = Util.toByteArray(response.body().asInputStream());
        String rawBody = new String(bodyData, StandardCharsets.UTF_8);

        // Security: Mask sensitive fields in the error response (e.g., error.details.password)
        audit.setResponseBody(jsonMasker.mask(rawBody));

        /*
         * CRITICAL: We must re-buffer the response body if the delegate needs to
         * read it again. However, since most decoders consume the body to create
         * the exception, we pass a new response builder to the delegate.
         */
        response = response.toBuilder().body(bodyData).build();
      }

      publisher.publishEvent(new ApiLogEvent(audit));
    } catch (IOException ignored) {
      // Failure to audit must never block the primary error propagation
    }

    // Delegate to the next decoder in the chain (Service Custom Decoder or Default)
    return delegate.decode(methodKey, response);
  }
}
