CREATE TABLE IF NOT EXISTS api_audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_name VARCHAR(255),
    type VARCHAR(20),
    method VARCHAR(10),
    description VARCHAR(255),
    url CLOB,
    query_string CLOB,
    request_headers CLOB,
    response_headers CLOB,
    request_body CLOB,
    response_body CLOB,
    http_status INT,
    duration BIGINT,
    correlation_id VARCHAR(100),
    client_ip VARCHAR(100),
    user_agent VARCHAR(512),
    principal_name VARCHAR(255),
    error_type VARCHAR(255),
    error_message CLOB,
    timestamp TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_audit_correlation ON api_audit_log(correlation_id);
CREATE INDEX IF NOT EXISTS idx_audit_timestamp ON api_audit_log(timestamp);


