CREATE TABLE api_audit_log (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_name VARCHAR2(255),
    type VARCHAR2(20),
    method VARCHAR2(10),
    description VARCHAR2(255),
    url CLOB,
    query_string CLOB,
    request_headers CLOB,
    response_headers CLOB,
    request_body CLOB,
    response_body CLOB,
    http_status NUMBER(10),
    duration NUMBER(19),
    correlation_id VARCHAR2(100),
    client_ip VARCHAR2(100),
    user_agent VARCHAR2(512),
    principal_name VARCHAR2(255),
    error_type VARCHAR2(255),
    error_message CLOB,
    timestamp TIMESTAMP
);
CREATE INDEX idx_audit_correlation ON api_audit_log(correlation_id);
CREATE INDEX idx_audit_timestamp ON api_audit_log(timestamp);


