CREATE TABLE IF NOT EXISTS api_audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_name VARCHAR(255),
    type VARCHAR(20),
    method VARCHAR(10),
    description VARCHAR(255),
    url TEXT,
    query_string TEXT,
    request_headers TEXT,
    response_headers TEXT,
    request_body TEXT,
    response_body TEXT,
    http_status INT,
    duration BIGINT,
    correlation_id VARCHAR(100),
    client_ip VARCHAR(100),
    user_agent VARCHAR(512),
    principal_name VARCHAR(255),
    error_type VARCHAR(255),
    error_message TEXT,
    timestamp TIMESTAMP WITHOUT TIME ZONE
);
CREATE INDEX IF NOT EXISTS idx_audit_correlation ON api_audit_log(correlation_id);
CREATE INDEX IF NOT EXISTS idx_audit_timestamp ON api_audit_log(timestamp);


