package com.api.audit.storage.jdbc;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.mock;

import com.api.audit.model.AuditLogRecord;
import com.api.audit.spi.AuditLogSearchStore;
import com.api.audit.spi.AuditLogStore;
import java.time.LocalDateTime;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.boot.autoconfigure.AutoConfigurations;
import org.springframework.boot.test.context.runner.ApplicationContextRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

/**
 * Integration-style tests for the plain JDBC audit store.
 *
 * <p>The table is created directly in H2 so this test stays focused on the store contract: saving
 * an {@link AuditLogRecord}, reading it back, and honoring the same search filters used by the
 * internal audit endpoint.
 *
 * @author Puneet Swarup
 */
class JdbcAuditLogStoreTest {

  private final ApplicationContextRunner contextRunner =
      new ApplicationContextRunner()
          .withConfiguration(AutoConfigurations.of(JdbcAuditLogAutoConfiguration.class))
          .withUserConfiguration(JdbcTemplateConfig.class);

  private JdbcTemplate jdbcTemplate;
  private JdbcAuditLogStore store;

  @BeforeEach
  void setUp() {
    DriverManagerDataSource dataSource = new DriverManagerDataSource();
    dataSource.setDriverClassName("org.h2.Driver");
    dataSource.setUrl("jdbc:h2:mem:jdbc-audit-test;DB_CLOSE_DELAY=-1;MODE=PostgreSQL");
    dataSource.setUsername("sa");
    dataSource.setPassword("");

    jdbcTemplate = new JdbcTemplate(dataSource);
    jdbcTemplate.execute("DROP TABLE IF EXISTS api_audit_log");
    jdbcTemplate.execute(
        """
        CREATE TABLE api_audit_log (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            service_name VARCHAR(255),
            type VARCHAR(20),
            method VARCHAR(10),
            description VARCHAR(100),
            url CLOB,
            query_string CLOB,
            request_headers CLOB,
            response_headers CLOB,
            request_body CLOB,
            response_body CLOB,
            http_status INT,
            duration BIGINT,
            correlation_id VARCHAR(50),
            client_ip VARCHAR(100),
            user_agent VARCHAR(512),
            principal_name VARCHAR(255),
            error_type VARCHAR(255),
            error_message CLOB,
            timestamp TIMESTAMP
        )
        """);

    store = new JdbcAuditLogStore(jdbcTemplate);
  }

  @Test
  void savesAndSearchesAuditRecordByCorrelationAndType() {
    LocalDateTime timestamp = LocalDateTime.of(2026, 5, 25, 3, 45);

    store.save(
        AuditLogRecord.builder()
            .serviceName("order-service")
            .type("OUTGOING")
            .method("POST")
            .description("CREATE_ORDER")
            .url("https://example.org/orders")
            .queryString("source=mobile")
            .requestHeaders("{\"Content-Type\":[\"application/json\"]}")
            .responseHeaders("{\"X-Result\":[\"accepted\"]}")
            .requestBody("{\"item\":\"book\"}")
            .responseBody("{\"status\":\"accepted\"}")
            .httpStatus(202)
            .duration(37)
            .correlationId("corr-jdbc-1")
            .clientIp("10.0.0.15")
            .userAgent("JUnit")
            .principalName("puneet")
            .errorType("HTTP_500")
            .errorMessage("Downstream failed")
            .timestamp(timestamp)
            .build());

    Page<AuditLogRecord> page =
        store.search(
            "corr-jdbc-1",
            timestamp.minusMinutes(1),
            timestamp.plusMinutes(1),
            "OUTGOING",
            "orders",
            "order-service",
            "POST",
            202,
            "10.0.0.15",
            "puneet",
            "HTTP_500",
            PageRequest.of(0, 10));

    assertThat(page.getTotalElements()).isEqualTo(1);
    AuditLogRecord record = page.getContent().getFirst();

    assertThat(record.getServiceName()).isEqualTo("order-service");
    assertThat(record.getType()).isEqualTo("OUTGOING");
    assertThat(record.getMethod()).isEqualTo("POST");
    assertThat(record.getDescription()).isEqualTo("CREATE_ORDER");
    assertThat(record.getUrl()).isEqualTo("https://example.org/orders");
    assertThat(record.getQueryString()).isEqualTo("source=mobile");
    assertThat(record.getRequestHeaders()).contains("Content-Type");
    assertThat(record.getResponseHeaders()).contains("X-Result");
    assertThat(record.getRequestBody()).isEqualTo("{\"item\":\"book\"}");
    assertThat(record.getResponseBody()).isEqualTo("{\"status\":\"accepted\"}");
    assertThat(record.getHttpStatus()).isEqualTo(202);
    assertThat(record.getDuration()).isEqualTo(37);
    assertThat(record.getCorrelationId()).isEqualTo("corr-jdbc-1");
    assertThat(record.getClientIp()).isEqualTo("10.0.0.15");
    assertThat(record.getUserAgent()).isEqualTo("JUnit");
    assertThat(record.getPrincipalName()).isEqualTo("puneet");
    assertThat(record.getErrorType()).isEqualTo("HTTP_500");
    assertThat(record.getErrorMessage()).isEqualTo("Downstream failed");
    assertThat(record.getTimestamp()).isEqualTo(timestamp);
  }

  @Test
  void autoConfigurationRegistersStoreOnlyWhenJdbcStorageSelected() {
    contextRunner.run(context -> assertThat(context).doesNotHaveBean(JdbcAuditLogStore.class));

    contextRunner
        .withPropertyValues("audit.logging.storage.type=jdbc")
        .run(
            context -> {
              assertThat(context).hasSingleBean(JdbcAuditLogStore.class);
              assertThat(context).hasSingleBean(AuditLogStore.class);
              assertThat(context).hasSingleBean(AuditLogSearchStore.class);
            });

    contextRunner
        .withPropertyValues("audit.logging.storage.type=memory")
        .run(context -> assertThat(context).doesNotHaveBean(JdbcAuditLogStore.class));
  }

  @Configuration(proxyBeanMethods = false)
  static class JdbcTemplateConfig {

    @Bean
    JdbcTemplate jdbcTemplate() {
      return mock(JdbcTemplate.class);
    }
  }
}
